language: node_js
node_js:
- '0.12'

env:
  global:
  - DEPLOY_BRANCH=master
  - STAGING_BRANCH=2017
  - secure: "uYdQRkIMLm9zOnOhCLnczYEhmj9vAdomAbh8/qIDxFLQ5l0fBTlpKTggsxUIZ06MPEFyAlQ7TVpLsPEPy9VwyIi9AE4PHTgo5iHFb1tiU92wmJew470lH8t92mGAP2CebcPf6cCqLBC8+i8uRl1w8USZGeqW+RJtlMwHlK9xBMo="

before_install:
  - chmod +x ./.build_scripts/deploy.sh

script:
  - $TRAVIS_BRANCH == ${DEPLOY_BRANCH} && npm run build
  - $TRAVIS_BRANCH == ${STAGING_BRANCH} && npm run stage

deploy:
  - provider: script
    skip_cleanup: true
    script: .build_scripts/deploy.sh
    on:
      branch: ${DEPLOY_BRANCH}
  - provider: s3
    access_key_id: AKIAIPCUDO7FIUH2RIUA
    secret_access_key:
      secure: S9itQQi8xhj/AHQIsnrntmBvVLgz8wds9NlsHXRhS0IZ1KNMZooYcfrkMrApB6j26vNvR2Ty4JgjJ/QYOhZSWTb8w0oi9Fo8KM+1c3E5OIFD7Kom/EveeJZiCk3oK098F9pLa9fO/vftjHwaF8IvfoTbJz/aNPvDQ1yAhb0TmEM=
    bucket: climatescope_staging
    region: us-west-2
    acl: public_read
    local-dir: _site
    skip-cleanup: true
    on:
      branch: ${STAGING_BRANCH}