safe:           false
domain:         http://localhost:4000
#domain:         http://demo.flipside.org/climatescope
name:
  en:           Climatescope
  es:           Climascopio
tagline:
  en:           Assessing the Climate for Climate Investment
  es:           Assessing the Climate for Climate Investment ES
description:
  en:           This is a custom description
  es:           This is a custom description ES
edition:        2014
exclude:        ['node_modules', 'source_assets', 'Gruntfile.js', 'package.json', 'README.md']
collections:
  en_region:
    output: true
    permalink: /en/region/:path/
    lang: en
    i18n:
      en: en_region
      es: es_region
    
  es_region:
    output: true
    permalink: /es/region/:path/
    lang: es
    i18n:
      en: en_region
      es: es_region
      
  en_country:
    output: true
    permalink: /en/country/:path/
    lang: en
    i18n:
      en: en_country
      es: es_country
      
  es_country:
    output: true
    permalink: /es/pais/:path/
    lang: es
    i18n:
      en: en_country
      es: es_country
      
  en_state:
    output: true
    permalink: /en/country/:path/
    lang: en
    i18n:
      en: en_state
      es: es_state
      
  es_state:
    output: true
    permalink: /es/pais/:path/
    lang: es
    i18n:
      en: en_state
      es: es_state
      
  en_parameter:
    output: true
    permalink: /en/topic/:path/
    lang: en
    i18n:
      en: en_parameter
      es: es_parameter
      
  es_parameter:
    output: true
    permalink: /es/tema/:path/
    lang: es
    i18n:
      en: en_parameter
      es: es_parameter

  en_page:
    output: true
    permalink: /en/:path/
    lang: en
    i18n:
      en: en_page
      es: es_page
      
  es_page:
    output: true
    permalink: /es/:path/
    lang: es
    i18n:
      en: en_page
      es: es_page
