safe:           false

# Domain and path_prefix are needed for IE9 CORS.
# More in: https://github.com/flipside-org/climatescope/issues/221
domain:         http://localhost:3000
path_prefix:    

# exclude:
#   - assets/scripts
#   - assets/vendor
#   - assets/styles
#   - _en_country/bangladesh.md
#   - _en_country/barbados.md
#   - _en_country/belize.md
#   - _en_country/bolivia.md
#   - _en_country/botswana.md
#   - _en_country/brazil.md
#   - _en_country/cameroon.md
#   - _en_country/chile.md
#   - _en_country/colombia.md
#   - _en_country/costa-rica.md
#   - _en_country/dominican-republic.md
#   - _en_country/dr-congo.md
#   - _en_country/ecuador.md
#   - _en_country/el-salvador.md
#   - _en_country/ethiopia.md
#   - _en_country/ghana.md
#   - _en_country/guatemala.md
#   - _en_country/guyana.md
#   - _en_country/haiti.md
#   - _en_country/honduras.md
#   - _en_country/india.md
#   - _en_country/indonesia.md
#   - _en_country/ivory-coast.md
#   - _en_country/jamaica.md
#   - _en_country/kenya.md
#   - _en_country/liberia.md
#   - _en_country/malawi.md
#   - _en_country/mexico.md
#   - _en_country/mozambique.md
#   - _en_country/myanmar.md
#   - _en_country/nepal.md
#   - _en_country/nicaragua.md
#   - _en_country/nigeria.md
#   - _en_country/pakistan.md
#   - _en_country/panama.md
#   - _en_country/paraguay.md
#   - _en_country/peru.md
#   - _en_country/rwanda.md
#   - _en_country/senegal.md
#   - _en_country/sierra-leone.md
#   - _en_country/south-africa.md
#   - _en_country/sri-lanka.md
#   - _en_country/suriname.md
#   - _en_country/tajikistan.md
#   - _en_country/tanzania.md
#   - _en_country/trinidad-and-tobago.md
#   - _en_country/uganda.md
#   - _en_country/uruguay.md
#   - _en_country/venezuela.md
#   - _en_country/vietnam.md
#   - _en_country/zambia.md
#   - _en_country/zimbabwe.md
#   - _es_country/banglades.md
#   - _es_country/barbados.md
#   - _es_country/belice.md
#   - _es_country/birmania.md
#   - _es_country/bolivia.md
#   - _es_country/botsuana.md
#   - _es_country/brasil.md
#   - _es_country/camerun.md
#   - _es_country/chile.md
#   - _es_country/colombia.md
#   - _es_country/costa-de-marfil.md
#   - _es_country/costa-rica.md
#   - _es_country/ecuador.md
#   - _es_country/el-salvador.md
#   - _es_country/etiopia.md
#   - _es_country/ghana.md
#   - _es_country/guatemala.md
#   - _es_country/guyana.md
#   - _es_country/haiti.md
#   - _es_country/honduras.md
#   - _es_country/india.md
#   - _es_country/indonesia.md
#   - _es_country/jamaica.md
#   - _es_country/kenia.md
#   - _es_country/liberia.md
#   - _es_country/malaui.md
#   - _es_country/mexico.md
#   - _es_country/mozambique.md
#   - _es_country/nepal.md
#   - _es_country/nicaragua.md
#   - _es_country/nigeria.md
#   - _es_country/pakistan.md
#   - _es_country/panama.md
#   - _es_country/paraguay.md
#   - _es_country/peru.md
#   - _es_country/rd-congo.md
#   - _es_country/republica-dominicana.md
#   - _es_country/ruanda.md
#   - _es_country/senegal.md
#   - _es_country/sierra-leona.md
#   - _es_country/sri-lanka.md
#   - _es_country/sudafrica.md
#   - _es_country/surinam.md
#   - _es_country/tanzania.md
#   - _es_country/tayikistan.md
#   - _es_country/trinidad-y-tobago.md
#   - _es_country/uganda.md
#   - _es_country/uruguay.md
#   - _es_country/venezuela.md
#   - _es_country/vietnam.md
#   - _es_country/zambia.md
#   - _es_country/zimbabue.md
#   - _en_page
#   - _es_page
#   - _en_parameter
#   - _es_parameter
#   - _en_state
#   - _es_state
#   - _en_region
#   - _es_region