safe:           false
domain:         http://localhost:4000
#domain:         http://demo.flipside.org/climatescope
name:           Global Climatescope 2014
exclude:        ['node_modules', 'source_assets', 'Gruntfile.js', 'package.json', 'README.md']
collections:
  en_region:
    output: true
    permalink: /en/region/:title/
    lang: en
    i18n:
      en: en_region
      es: es_region
    
  es_region:
    output: true
    permalink: /es/region/:title/
    lang: es
    i18n:
      en: en_region
      es: es_region
      
  en_country:
    output: true
    permalink: /en/country/:title/
    lang: en
    i18n:
      en: en_country
      es: es_country
      
  es_country:
    output: true
    permalink: /es/pais/:title/
    lang: es
    i18n:
      en: en_country
      es: es_country
      
  en_state:
    output: true
    permalink: /en/country/:path/
    lang: en
    i18n:
      en: en_state
      es: es_state
      
  es_state:
    output: true
    permalink: /es/pais/:path/
    lang: es
    i18n:
      en: en_state
      es: es_state
      
  en_parameter:
    output: true
    permalink: /en/topic/:title/
    lang: en
    i18n:
      en: en_parameter
      es: es_parameter
      
  es_parameter:
    output: true
    permalink: /es/tema/:title/
    lang: es
    i18n:
      en: en_parameter
      es: es_parameter

  en_page:
    output: true
    permalink: /en/:title/
    lang: en
    i18n:
      en: en_page
      es: es_page
      
  es_page:
    output: true
    permalink: /es/:title/
    lang: es
    i18n:
      en: en_page
      es: es_page
