safe:           false
domain:         http://localhost:4000
#domain:         http://demo.flipside.org/climatescope
name:
  en:           Global Climatescope
  es:           Climascopio Global
tagline:
  en:           Assessing the Climate for Climate Investment
  es:           Assessing the Climate for Climate Investment ES
edition:        2014
exclude:        ['node_modules', 'source_assets', 'Gruntfile.js', 'package.json', 'README.md']
collections:
  en_region:
    output: true
    permalink: /en/region/:path/
    lang: en
    i18n:
      en: en_region
      es: es_region
    layout_vars:
      type: region
      subtitle: Region
      include_map: true
    
  es_region:
    output: true
    permalink: /es/region/:path/
    lang: es
    i18n:
      en: en_region
      es: es_region
    layout_vars:
      type: region
      subtitle: Región
      include_map: true
      
  en_country:
    output: true
    permalink: /en/country/:path/
    lang: en
    i18n:
      en: en_country
      es: es_country
    layout_vars:
      type: country
      subtitle: Country
      
  es_country:
    output: true
    permalink: /es/pais/:path/
    lang: es
    i18n:
      en: en_country
      es: es_country
    layout_vars:
      type: country
      subtitle: Country
      
  en_state:
    output: true
    permalink: /en/country/:path/
    lang: en
    i18n:
      en: en_state
      es: es_state
    layout_vars:
      type: state
      subtitle: State
      
  es_state:
    output: true
    permalink: /es/pais/:path/
    lang: es
    i18n:
      en: en_state
      es: es_state
    layout_vars:
      type: state
      subtitle: State
      
  en_parameter:
    output: true
    permalink: /en/topic/:path/
    lang: en
    i18n:
      en: en_parameter
      es: es_parameter
    layout_vars:
      type: parameter
      subtitle: Parameter
      
  es_parameter:
    output: true
    permalink: /es/tema/:path/
    lang: es
    i18n:
      en: en_parameter
      es: es_parameter
    layout_vars:
      type: parameter
      subtitle: Parameter

  en_page:
    output: true
    permalink: /en/:path/
    lang: en
    i18n:
      en: en_page
      es: es_page
    layout_vars:
      type: page
      
  es_page:
    output: true
    permalink: /es/:path/
    lang: es
    i18n:
      en: en_page
      es: es_page
    layout_vars:
      type: page
