source: app
exclude:
  - assets/scripts
  - assets/styles
  - assets/icons
baseurl: //global-climatescope.org
kramdown:
  input: GFM
  syntax_highlighter: rouge

# SEO defaults:
# Everything is handled through javascript. Check assets/scripts/config

collections:
  pages:
    output: true