source: app
exclude:
  - assets/scripts
  - assets/styles
  - assets/icons
baseurl: http://global-climatescope.org
kramdown:
  input: GFM
  syntax_highlighter: rouge

# SEO defaults:
# Everything is handled through javascript. Check assets/scripts/config