version: 2
jobs:
  build:
    docker:
      - image: developmentseed/developmentseed.org:slim
    working_directory: ~/developmentseed.github.com

    environment:
      - PRODUCTION_BRANCH: publish
      - GH_BRANCH: master
      - GH_REF: git@github.com:developmentseed/developmentseed.github.com.git
      - GH_NAME: "Development Seed"
      - GH_EMAIL: "dev@developmentseed.org"

    steps:
      - checkout

      # restore cache
      - restore_cache:
          keys:
            - developmentseedorg-{{ .Branch }}-{{ checksum "package.json" }}
            - developmentseedorg-{{ .Branch }}
            - developmentseedorg

      - run:
          name: Installing Dependencies
          command: |
            yarn install --unsafe-perm


      - run:
          name: Running Test
          command: |
            yarn test

      - run:
          name: Compressing images
          command: |
             if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
               yarn images
             else
               echo "Skip compressing images"
             fi


      - run:
          name: Building site
          command: |
             if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
               yarn build
             else
               echo "Skip building site"
             fi

      - add_ssh_keys:
          fingerprints:
             - "91:52:74:4b:a5:48:3d:dc:5d:f0:38:37:c8:45:d5:5f"
      - run:
         name: Deploying to Github
         command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
               cd _site
               git init
               git config user.name "$GH_NAME"
               git config user.email "$GH_EMAIL"
               touch .nojekyll # Add this so GitHub doesn't try and build site
               git add .
               git commit -m "CI deploy [skip ci]"
               git remote add origin $GH_REF
               git push origin --force --quiet HEAD:$GH_BRANCH
               rm -rf .git
             else
               echo "Skip deploying to Github"
            fi

      # save node_module folders
      - save_cache:
          key: developmentseedorg-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/developmentseed.github.com/node_modules
            - ~/developmentseed.github.com/src/assets/bower_components
            - ~/developmentseed.github.com/src/assets/graphics/content
            - ~/developmentseed.github.com/.tmp

