version: 2
jobs:
  build:
    docker:
      - image: developmentseed/developmentseed.org:slim

    working_directory: ~/repo

    environment:
      - STAGING_BRANCH: v2018
      - PRODUCTION_BRANCH: v2018

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run:
          name: Building site staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "${STAGING_BRANCH}" ]; then
              yarn build-stage
            else
              echo "Skip building site"
            fi

      - run:
          name: Deploy to Surge staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "${STAGING_BRANCH}" ]; then
              cp ./_site/index.html ./_site/200.html
              ./node_modules/surge/lib/cli.js --project ./_site --domain climatescope.surge.sh
            else
              echo "Not the branch you're looking for, skipping deploy"
            fi

      - run:
          name: Building site prod
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              yarn build
            else
              echo "Skip building site"
            fi

      - run:
          name: Deploy to Surge prod
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              cp ./_site/index.html ./_site/200.html
              echo "global-climatescope.org" > ./_site/CNAME
              ./node_modules/surge/lib/cli.js --project ./_site --domain global-climatescope.org
            else
              echo "Not the branch you're looking for, skipping deploy"
            fi
